[project]
name = 'Blockchain-Enabled-Rural-Healthcare-Coordination'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.patient-matching]
path = 'contracts/patient-matching.clar'
clarity_version = 2
epoch = 2.5

[contracts.provider-registration]
path = 'contracts/provider-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.telehealth-facilitation]
path = 'contracts/telehealth-facilitation.clar'
clarity_version = 2
epoch = 2.5

[contracts.transportation-coordination]
path = 'contracts/transportation-coordination.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
